module.exports={
    USER_COLLECTION:'user',
    CLUB_COLLECTION:'club',
    COACH_COLLECTION:'coach',
    PLAYER_COLLECTION:'player',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    GROUND_COLLECTION:'grounds',
    GROUNDBOOKING_COLLECTION:'groundbooking', 
    TICKETBOOKING_COLLECTION:'ticketbooking', 
}